/**
 * In-app usage guide (Traditional Chinese), organized to mirror the demo flow:
 * one 大項 (section) per stage, one 小項 (feature) at a time.
 *
 * `shot` names a screenshot in /guide/<shot> (generated by
 * demo/capture-guide-shots — missing files are hidden gracefully).
 * `demo` names the example choreography to open from the Library first.
 */

export interface GuideFeature {
  title: string;
  body: string[];
  tip?: string;
  shot?: string;
}

export interface GuideSection {
  id: string;
  title: string;
  intro?: string;
  demo?: string;
  features: GuideFeature[];
}

export const GUIDE: GuideSection[] = [
  {
    id: 'stage',
    title: '0 · 舞台設定',
    intro: '每支舞碼開始前，先把舞台設定好——這些只需要在建立時做一次，之後都收在「舞台設定」裡。',
    features: [
      {
        title: '新建一支舞碼',
        body: [
          '點左上角的 Library → New choreography。',
          '填入標題、選一個舞台尺寸預設（proscenium 12×8、教室、黑箱、體育館，或自訂），按 Create。',
        ],
      },
      {
        title: '舞台設定對話框',
        body: [
          '打開 Stage settings，可以調整舞台長寬、觀眾席方位、側台、以及背景照片。',
          '這些設定之後隨時能回來改，不用重建舞碼。',
        ],
        shot: 's0-stage-settings.png',
      },
      {
        title: '觀眾席方位',
        body: [
          'bottom＝導演視角（預設）；top＝表演者自己的視角，畫面會翻轉 180°。',
          '只是「看的角度」不同，實際座標不會改變。',
        ],
      },
      {
        title: '側台 wings',
        body: ['設定左、右、後方的等待區寬度後，舞者就能暫時站到舞台之外（上場前的候場位置）。'],
      },
      {
        title: '舞台背景照片',
        body: ['上傳實際場地的照片墊在網格底下，並可調整透明度，方便對照真實舞台。'],
      },
    ],
  },
  {
    id: 'workspace',
    title: '1 · 畫面工作區',
    intro: '先認識畫面的四大區塊，後面操作就不會迷路。',
    features: [
      {
        title: '版面配置',
        body: [
          '上方＝工具列（標題、Library、分享、匯出、⚙）。',
          '左＝卡司 Cast、中＝舞台畫布、右＝屬性面板、下＝時間軸。',
        ],
        shot: 's1-workspace.png',
      },
      {
        title: 'easy／expert 模式',
        body: [
          '在 ⚙ 偏好設定裡切換。',
          'easy 只留核心功能給新手；expert 打開全部進階工具（班底、道具、解交叉、隊形庫…）。',
        ],
        tip: '第一次上手用 easy，熟了再切 expert。',
      },
      {
        title: '畫布工具列',
        body: ['畫布右下角：Snap 網格吸附、Pen 畫筆、Note 圖釘、3D 立體切換。'],
      },
      {
        title: '復原與重做',
        body: ['上方 Undo／Redo 按鈕，或鍵盤 Ctrl+Z／Ctrl+Shift+Z。'],
      },
    ],
  },
  {
    id: 'music',
    title: '2 · 音樂與 Formation',
    intro: '匯入音樂，讓走位跟著節拍走。',
    demo: 'Demo · Paths & Facing',
    features: [
      {
        title: '匯入音檔',
        body: ['在時間軸按 Upload audio 選音樂檔，載入後時間軸會顯示波形。'],
      },
      {
        title: '設定 BPM 與打拍',
        body: [
          '在節拍對話框輸入每分鐘拍數（BPM）。',
          '不知道拍速？用 Tap tempo 跟著音樂點幾下，系統會幫你算出來。',
        ],
      },
      {
        title: '拍點與計數段落',
        body: [
          '標記 beat markers（拍點），並劃定用 8 拍計數的段落。',
          '音樂常常不是從第 1 拍開始，每段可以各自對齊自己的第 1 拍。',
        ],
      },
      {
        title: '節拍器',
        body: ['播放時開啟節拍器，會發出點擊聲幫你對拍。'],
      },
      {
        title: 'Formation 與時間軸',
        body: [
          '時間軸上每個方塊就是一個 formation。',
          '拖動方塊可以改變它出現的時間點；按播放就能看到走位動畫。',
        ],
      },
    ],
  },
  {
    id: 'solo',
    title: '3 · 單一人物設定',
    intro: '選一位舞者，設定他的位置、面向與移動路徑。',
    demo: 'Demo · Paths & Facing',
    features: [
      {
        title: '選取與屬性',
        body: [
          '點畫布上的舞者，右側屬性面板就會顯示他的設定。',
          '可改位置 x／y、名字、顏色、角色、以及名牌 badge（標在圖示上的一個字）。',
        ],
      },
      {
        title: '面向角度',
        body: [
          'rotation 是舞者的朝向：0 度＝面向觀眾，順時針為正。',
          '範例三個 formation 面向各不相同，示範同一人在不同段落轉向。',
        ],
        shot: 's3-curve-path.png',
      },
      {
        title: '直線 vs 曲線路徑',
        body: [
          '每個 formation 可選擇過場方式：linear（直線）或 curve（曲線）。',
          'curve 會沿著一個控制點畫出弧線。範例的 Formation 1→2 是直線、2→3 是曲線，播放時看得出差別。',
        ],
      },
      {
        title: '整場路線',
        body: ['開啟「Show whole-show path」，看這位舞者整場的移動路線：編號停點加上虛線。'],
      },
      {
        title: '狀態記號',
        body: [
          '在屬性面板的「狀態記號」選一個形狀（方形／三角形／菱形），舞者的圖示外圍就會多一圈記號。',
          '記號只屬於「目前這個 formation」——同一位舞者可以在第 3 段標成蹲下、第 4 段拿道具。意義由團隊自己約定。',
        ],
        tip: '播放時記號會暫時隱藏，因為過場途中「狀態」沒有明確定義。',
      },
    ],
  },
  {
    id: 'ensemble',
    title: '4 · 多人設定',
    intro: '人多的時候，用範本和群組快速排出漂亮隊形。',
    demo: 'Demo · Five Dancers',
    features: [
      {
        title: '範本 templates',
        body: ['一鍵套用常見形狀：直線、V 字、圓形、方陣。'],
        shot: 's4-formation.png',
      },
      {
        title: '隊形庫 presets',
        body: ['把目前的隊形存起來，之後一鍵套用到別的 formation，不用重排。'],
      },
      {
        title: '群組與班底',
        body: [
          '給舞者貼標籤分組，一鍵選取整組（例如「前排」「flyers」）。',
          'Crews 班底則能把整份卡司存起來，換舞碼時重複使用。',
        ],
      },
      {
        title: '對齊、分佈、鏡射、交換',
        body: ['讓一排對齊、平均分佈間距、左右鏡射整個隊形，或把兩人的位置互換。'],
      },
      {
        title: '群組旋轉與散開／收攏',
        body: [
          '選取多位舞者後，可以以群組中心為軸整組旋轉（每按一次 15°，面向跟著轉）。',
          '「散開」把間距拉大、「收攏」把間距縮小，隊形形狀保持不變。',
        ],
      },
      {
        title: '框選群拖與解交叉',
        body: [
          '在空白處拖曳框選多位舞者，一起移動。',
          'Untangle 會自動把互相交叉的走位換成最短、不打結的路徑。',
        ],
      },
      {
        title: 'Formation 建議',
        body: ['系統會依現有人數給幾個隊形建議，附上小預覽，點一下就套用。'],
      },
    ],
  },
  {
    id: 'view',
    title: '5 · 檢視畫面（2D／3D）',
    intro: '從不同視角檢查走位是否合理。',
    demo: 'Demo · Five Dancers',
    features: [
      {
        title: '觀眾席視角',
        body: ['2D 可在導演視角與表演者視角之間切換，確認台上台下看到的樣子。'],
      },
      {
        title: '3D 預覽',
        body: ['按 3D 進入立體場景，直觀看到舞者在空間中的相對位置與間距。'],
        shot: 's5-3d.png',
      },
      {
        title: '鏡頭預設與跟拍',
        body: ['切換觀眾／俯視／側面鏡頭，或選擇跟拍某一位舞者的視角。'],
      },
      {
        title: '過場分析',
        body: [
          '系統會自動警告過場時可能的碰撞、或移動速度過快。',
          '範例的曲線段落正好可能觸發，方便你看到警告長怎樣。',
        ],
      },
    ],
  },
  {
    id: 'export',
    title: '6 · 影片與檔案匯出',
    intro: '把成果輸出成影片或 PDF，交給團隊。',
    features: [
      {
        title: '走位動畫（MP4）',
        body: ['匯出 2D 或 3D 的走位動畫影片，並可混入音樂。'],
        shot: 's6-export.png',
      },
      {
        title: 'PDF 走位圖＋名冊',
        body: ['每個 formation 的走位圖加上演出名單，支援中文姓名。'],
      },
      {
        title: '個人走位單與排練包',
        body: [
          '每位舞者一頁的個人路線表。',
          '排練包 rehearsal pack 則把走位圖與所有個人單整合成一份 PDF。',
        ],
      },
      {
        title: 'PNG 定格',
        body: ['把目前選取的 formation 匯出成單張圖片。'],
      },
      {
        title: '編舞檔案（JSON）與備份',
        body: [
          '「匯出 → 檔案」把整份編舞存成一個 .gridstage.json，可以傳給別人，或當備份。',
          '對方（或你自己）用「文件庫 → 匯入檔案」帶回來，會以新的一份加入，不會覆蓋原有作品。',
          '注意：作品平常只存在瀏覽器裡，清除瀏覽資料就沒了——系統累積一定內容後每週會提醒你匯出備份。',
        ],
        tip: '音樂與背景圖不包含在檔案內，匯入後要重新上傳。',
      },
    ],
  },
];
